### ISSUE TITLE
ASP.NET Core Web API template

### ISSUE THREAD

**Issue by lockhartsoftware** [aksoftware98/ticketsbasket#2]
Hi Ahmad,

In Video 10 'TicketsBasket: Authentication with Azure AD B2C - Creating the ASP.NET Core API Project' when creating the API, I added the New Project using the Project Template 'ASP.NET Core Web API' since the 'ASP.NET Core Web App' in .NET 5 doesn't allow me to specify an API.

I also specified Authentication as 'Microsoft identity platform' as there was no Individual User Account in the Authentication Type dropdown as in your video. There was also no opportunity to enter the Azure AD B2C details as in your video.

The structure of my API app looks different from your API app. For example, my dependency packages are:

Microsoft.AspNetCore.Authentication.JwtBearer
Microsoft.AspNetCore.Authentication.OpenIdConnect
Microsoft.Identity.Web
Swashbuckle.AspNetCore

which is different from your API app.

Will this work? If not, how can I make it work, please?

Obviously the technology has changed since you recorded the video.

Thanks in advance.

Kind Regards

Walter

PS., it looks like it has pre-configured the API as Azure AD.

In Startup.cs I have:

            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApi(Configuration.GetSection("AzureAd"));

I think I've messed it up.

Will I use ASP.NET Core Web App instead?

**Comment by aksoftware98** [comment]
Hi dear 
Thank you so much for reaching 
Actually, when I created this course the .NET Core 3.1 was the official release of .NET and things then was a little different from now, In addition to this, I have created a separated Blazor WebAssembly Project & a separated ASP.NET Core Web API the best way to follow along with this course that will be continued starting from the upcoming three days is to watch the following video and create the project exactly as I will do here.
https://www.youtube.com/watch?v=S5PRH_N7pag

In this case, I have created a Blazor WebAssembly ASP.NET Core hosted which means the project will include the client, server, and shared project and you can setup the identity as I will do and then you can move back to the Tickets Basket course and continue from there with the business logic and other stuff.

Because also from that time the Visual Studio changed how it shows the template and the way you create a new project so I highly recommend you follow the video mentioned above and you will be ready to go.

As well as that Visual Studio still doesn't support creating a Blazor WebAssembly with .NET Core hosted project directly from the UI so the best way to do it as I did in the video using the .NET CLI

Hope this gonna help you and stay tuned for the new videos very soon

Thanks a lot let me know if you need any kind of help

**Comment by lockhartsoftware** [comment]
Thank you. I will try this.

**Comment by lockhartsoftware** [comment]
That is working well. Thank you. I can continue with the TicketsBasket application.

**Comment by aksoftware98** [comment]
That's great happy to hear that 

I will close this issue for now, feel free to open a new one for any reason or problem you have, thanks a lot
